from lesion_bank.views.views_overall import *
from lesion_bank.views.symptoms import *
from lesion_bank.views.new_symptom import *
from lesion_bank.views.import_data import *
from lesion_bank.views.genericFunctions import *
from lesion_bank.views.charts import *
from lesion_bank.views.api import *
from lesion_bank.views.practice import *
from lesion_bank.views.predict import *
from lesion_bank.views.single_case_view import *
from lesion_bank.views.symptom_detail_view import *
from lesion_bank.views.locations_view import *