from lesion_bank.views.views_overall import *
from lesion_bank.views.symptoms import *
from lesion_bank.views.import_data import *
from lesion_bank.views.charts import *
from lesion_bank.views.api import *
from lesion_bank.views.practice import *
from lesion_bank.views.predict import *
from lesion_bank.views.cases import *
from lesion_bank.views.locations import *
from lesion_bank.views.testing import *