# Generated by Django 4.1.1 on 2023-06-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0002_uploadedcoordinatestest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedCoordinates',
        ),
        migrations.DeleteModel(
            name='UploadedCoordinatesTest',
        ),
    ]
