# Generated by Django 4.1.1 on 2023-06-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesion_bank', '0003_delete_uploadedcoordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadID', models.CharField(max_length=30, null=True)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('z', models.FloatField(null=True)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
