# Generated by Django 4.1.1 on 2023-06-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0006_lesionmetadata_symptoms_delete_uploadedcoordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatestracings',
            name='lesion_id',
        ),
        migrations.RemoveField(
            model_name='coordinatesuploaded',
            name='upload_id',
        ),
        migrations.RemoveField(
            model_name='lesionmetadata',
            name='symptoms',
        ),
        migrations.DeleteModel(
            name='CoordinatesNetworks',
        ),
        migrations.DeleteModel(
            name='CoordinatesTracings',
        ),
        migrations.DeleteModel(
            name='CoordinatesUploaded',
        ),
        migrations.DeleteModel(
            name='LesionMetadata',
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
    ]
