# Generated by Django 4.1.1 on 2023-06-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesion_bank', '0007_remove_coordinatestracings_lesion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LesionMetadata',
            fields=[
                ('lesion', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('cause_of_lesion', models.CharField(blank=True, max_length=100, null=True)),
                ('original_image', models.CharField(blank=True, max_length=100, null=True)),
                ('original_image_2', models.CharField(blank=True, max_length=100, null=True)),
                ('original_image_3', models.CharField(blank=True, max_length=100, null=True)),
                ('original_image_4', models.CharField(blank=True, max_length=100, null=True)),
                ('tracing_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('network_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('symptoms', models.ManyToManyField(to='lesion_bank.symptoms')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatesUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('z', models.FloatField(null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('lesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.lesionmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatesTracings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('z', models.FloatField(null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('lesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.lesionmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatesNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('z', models.FloatField(null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('lesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.lesionmetadata')),
            ],
        ),
    ]
