# Generated by Django 4.1.1 on 2023-06-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatestracings',
            name='lesion',
        ),
        migrations.RemoveField(
            model_name='coordinatesuploaded',
            name='lesion',
        ),
        migrations.RemoveField(
            model_name='lesionmetadata',
            name='symptoms',
        ),
        migrations.DeleteModel(
            name='CoordinatesNetworks',
        ),
        migrations.DeleteModel(
            name='CoordinatesTracings',
        ),
        migrations.DeleteModel(
            name='CoordinatesUploaded',
        ),
        migrations.DeleteModel(
            name='LesionMetadata',
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
    ]
