# Generated by Django 4.1.1 on 2023-06-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0021_lesionmetadata_symptoms_voxelsuploaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voxelsnetworks',
            name='lesion',
        ),
        migrations.RemoveField(
            model_name='voxelsnetworks',
            name='voxel',
        ),
        migrations.RemoveField(
            model_name='voxelstracings',
            name='lesion',
        ),
        migrations.RemoveField(
            model_name='voxelstracings',
            name='voxel',
        ),
        migrations.RemoveField(
            model_name='voxelsuploaded',
            name='lesion',
        ),
        migrations.RemoveField(
            model_name='voxelsuploaded',
            name='voxel',
        ),
        migrations.DeleteModel(
            name='LesionMetadata',
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
        migrations.DeleteModel(
            name='VoxelsNetworks',
        ),
        migrations.DeleteModel(
            name='VoxelsTracings',
        ),
        migrations.DeleteModel(
            name='VoxelsUploaded',
        ),
    ]
