# Generated by Django 4.1.1 on 2023-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0026_lesionmetadata_patient_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='uploads/')),
                ('image_upload', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
