# Generated by Django 4.1.1 on 2023-06-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0027_fileuploadtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='symptom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
