# Generated by Django 4.1.1 on 2023-06-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0028_alter_symptoms_description_alter_symptoms_symptom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesionmetadata',
            old_name='patient_gender',
            new_name='patient_sex',
        ),
        migrations.AlterField(
            model_name='lesionmetadata',
            name='lesion_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesionmetadata',
            name='network_file_name',
            field=models.FileField(blank=True, null=True, upload_to='uploads/nifti_files'),
        ),
        migrations.AlterField(
            model_name='lesionmetadata',
            name='original_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/original_images'),
        ),
        migrations.AlterField(
            model_name='lesionmetadata',
            name='original_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/original_images'),
        ),
        migrations.AlterField(
            model_name='lesionmetadata',
            name='original_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/original_images'),
        ),
        migrations.AlterField(
            model_name='lesionmetadata',
            name='original_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/original_images'),
        ),
        migrations.AlterField(
            model_name='lesionmetadata',
            name='tracing_file_name',
            field=models.FileField(null=True, upload_to='uploads/nifti_files'),
        ),
    ]
