# Generated by Django 4.1.1 on 2023-06-30 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0030_delete_fileuploadtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesionmetadata',
            name='tracing_file_name',
            field=models.FileField(blank=True, null=True, upload_to='uploads/nifti_files'),
        ),
        migrations.AlterModelTable(
            name='coordinates',
            table='coordinates',
        ),
        migrations.AlterModelTable(
            name='lesionmetadata',
            table='metadata',
        ),
        migrations.AlterModelTable(
            name='symptoms',
            table='symptoms',
        ),
        migrations.AlterModelTable(
            name='voxelsnetworks',
            table='voxels_networks',
        ),
        migrations.AlterModelTable(
            name='voxelstracings',
            table='voxels_tracings',
        ),
        migrations.AlterModelTable(
            name='voxelsuploaded',
            table='voxels_uploaded',
        ),
        migrations.CreateModel(
            name='VoxelsAtlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('lesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.lesionmetadata')),
                ('voxel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.coordinates')),
            ],
            options={
                'db_table': 'voxels_atlas',
            },
        ),
    ]
