# Generated by Django 4.1.1 on 2023-06-30 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0031_alter_lesionmetadata_tracing_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesionmetadata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionmetadata',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
