# Generated by Django 4.1.1 on 2023-06-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0032_lesionmetadata_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'atlas_voxels',
            },
        ),
        migrations.CreateModel(
            name='AtlasKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'atlas_key',
            },
        ),
        migrations.CreateModel(
            name='AtlasMetadata',
            fields=[
                ('atlas_id', models.AutoField(primary_key=True, serialize=False)),
                ('atlas_name', models.CharField(blank=True, max_length=100, null=True)),
                ('atlas_file_name', models.FileField(blank=True, null=True, upload_to='uploads/atlas_files')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'atlas_metadata',
            },
        ),
        migrations.RenameModel(
            old_name='VoxelsNetworks',
            new_name='NetworkVoxels',
        ),
        migrations.RenameModel(
            old_name='VoxelsTracings',
            new_name='TraceVoxels',
        ),
        migrations.RenameModel(
            old_name='VoxelsUploaded',
            new_name='UploadedVoxels',
        ),
        migrations.AlterField(
            model_name='lesionmetadata',
            name='network_file_name',
            field=models.FileField(blank=True, null=True, upload_to='uploads/lesion_files'),
        ),
        migrations.AlterField(
            model_name='lesionmetadata',
            name='tracing_file_name',
            field=models.FileField(blank=True, null=True, upload_to='uploads/lesion_files'),
        ),
        migrations.AlterModelTable(
            name='networkvoxels',
            table='network_voxels',
        ),
        migrations.AlterModelTable(
            name='tracevoxels',
            table='trace_voxels',
        ),
        migrations.AlterModelTable(
            name='uploadedvoxels',
            table='uploaded_voxels',
        ),
        migrations.DeleteModel(
            name='VoxelsAtlas',
        ),
        migrations.AddField(
            model_name='atlaskey',
            name='atlas_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.atlasmetadata'),
        ),
        migrations.AddField(
            model_name='atlasdata',
            name='atlas_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.atlasmetadata'),
        ),
        migrations.AddField(
            model_name='atlasdata',
            name='voxel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.coordinates'),
        ),
    ]
