# Generated by Django 4.1.1 on 2023-06-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0033_atlasdata_atlaskey_atlasmetadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atlaskey',
            old_name='atlas_id',
            new_name='atlas',
        ),
    ]
