# Generated by Django 4.1.1 on 2023-06-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0035_rename_atlasdata_atlasvoxels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlaskey',
            name='key',
        ),
        migrations.RemoveField(
            model_name='atlasvoxels',
            name='value',
        ),
        migrations.AddField(
            model_name='atlaskey',
            name='key_id',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='atlasvoxels',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.atlaskey'),
        ),
    ]
