# Generated by Django 4.1.1 on 2023-06-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0036_remove_atlaskey_key_remove_atlasvoxels_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlasvoxels',
            name='key',
        ),
        migrations.AddField(
            model_name='atlasvoxels',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
