# Generated by Django 4.1.1 on 2023-07-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0039_uploadedimages_uploadedimagevoxels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='file_path',
            field=models.FileField(upload_to='uploads/upload_data'),
        ),
    ]
