# Generated by Django 4.1.1 on 2023-07-04 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesion_bank', '0040_alter_uploadedimages_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.IntegerField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='uploads/upload_data')),
                ('true_file_path', models.FileField(upload_to='uploads/upload_data')),
                ('file_size', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_images',
            },
        ),
        migrations.CreateModel(
            name='PracticeImageVoxels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('upload_id', models.ForeignKey(db_column='upload', on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.practiceimages')),
                ('voxel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.coordinates')),
            ],
            options={
                'db_table': 'practice_image_voxels',
            },
        ),
        migrations.CreateModel(
            name='TrueImageVoxels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('upload_id', models.ForeignKey(db_column='upload', on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.practiceimages')),
                ('voxel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.coordinates')),
            ],
            options={
                'db_table': 'true_image_voxels',
            },
        ),
        migrations.DeleteModel(
            name='UploadedVoxels',
        ),
    ]
