# Generated by Django 4.1.1 on 2023-07-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0041_practiceimages_practiceimagevoxels_trueimagevoxels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceimages',
            name='id',
        ),
        migrations.AlterField(
            model_name='practiceimages',
            name='upload',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
