# Generated by Django 4.1.1 on 2023-07-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0042_remove_practiceimages_id_alter_practiceimages_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceimages',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='practiceimagevoxels',
            name='upload_id',
        ),
        migrations.AddField(
            model_name='practiceimages',
            name='upload_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practiceimagevoxels',
            name='upload',
            field=models.ForeignKey(db_column='upload_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.practiceimages'),
        ),
        migrations.AlterField(
            model_name='trueimagevoxels',
            name='upload_id',
            field=models.ForeignKey(db_column='upload_id', on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.practiceimages'),
        ),
    ]
