# Generated by Django 4.1.1 on 2023-07-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0043_remove_practiceimages_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trueimagevoxels',
            name='upload_id',
        ),
        migrations.AddField(
            model_name='trueimagevoxels',
            name='upload',
            field=models.ForeignKey(db_column='upload_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.practiceimages'),
        ),
    ]
