# Generated by Django 4.1.1 on 2023-07-05 18:13

from django.db import migrations, models
import lesion_bank.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0044_remove_trueimagevoxels_upload_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceimages',
            name='file_path',
            field=models.FileField(upload_to=lesion_bank.models.PathAndRename('uploads/upload_data')),
        ),
        migrations.AlterField(
            model_name='practiceimages',
            name='true_file_path',
            field=models.FileField(upload_to=lesion_bank.models.PathAndRename('uploads/upload_data')),
        ),
    ]
