# Generated by Django 4.1.1 on 2023-07-06 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesion_bank', '0045_alter_practiceimages_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImages',
            fields=[
                ('file_id', models.CharField(db_column='file_id', max_length=10, primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='output/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_images',
            },
        ),
    ]
