# Generated by Django 4.1.1 on 2023-07-13 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0046_generatedimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionVoxels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.generatedimages')),
                ('voxel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesion_bank.coordinates')),
            ],
            options={
                'db_table': 'prediction_voxels',
            },
        ),
    ]
