# Generated by Django 4.1.1 on 2023-07-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0047_predictionvoxels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionvoxels',
            name='voxel',
            field=models.CharField(max_length=20),
        ),
    ]
