# Generated by Django 4.1.1 on 2023-07-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0048_alter_predictionvoxels_voxel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionvoxels',
            old_name='voxel',
            new_name='voxel_id',
        ),
    ]
