# Generated by Django 4.1.1 on 2023-08-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0049_rename_voxel_predictionvoxels_voxel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='sensitivity_map_path',
            field=models.FileField(blank=True, null=True, upload_to='sensitivity_maps'),
        ),
    ]
