# Generated by Django 4.1.1 on 2023-08-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0050_symptoms_sensitivity_map_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptoms',
            old_name='sensitivity_map_path',
            new_name='sensitivity_neg_path',
        ),
        migrations.AddField(
            model_name='symptoms',
            name='sensitivity_pos_path',
            field=models.FileField(blank=True, null=True, upload_to='sensitivity_maps'),
        ),
    ]
