# Generated by Django 4.1.1 on 2023-09-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0051_rename_sensitivity_map_path_symptoms_sensitivity_neg_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitivityVoxels',
            fields=[
                ('voxel_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('symptom_id', models.IntegerField()),
                ('positive_overlap_count', models.IntegerField()),
                ('negative_overlap_count', models.IntegerField()),
                ('overlap_difference', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('percent_overlap', models.FloatField()),
            ],
            options={
                'db_table': 'sensitivity_voxels',
                'managed': False,
            },
        ),
    ]
