# Generated by Django 4.1.1 on 2023-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_bank', '0052_sensitivityvoxels'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='sensitivity_parametric_path',
            field=models.FileField(blank=True, null=True, upload_to='sensitivity_maps'),
        ),
    ]
